export const GET_CONVERSATION_REQ = "GET_CONVERSATION_REQ";
export const GET_CONVERSATION_SUCCESS = "GET_CONVERSATION_SUCCESS";
export const GET_CONVERSATION_FAIL = "LGET_CONVERSATION_FAIL";

export const CREATE_CONVERSATION_REQ = "CREATE_CONVERSATION_REQ";
export const CREATE_CONVERSATION_SUCCESS = "CREATE_CONVERSATION_SUCCESS";
export const CREATE_CONVERSATION_FAIL = "LCREATE_CONVERSATION_FAIL";

export const GET_MESSAGE_REQ = "GET_MESSAGE_REQ";
export const GET_MESSAGE_SUCCESS = "GET_MESSAGE_SUCCESS";
export const GET_MESSAGE_FAIL = "LGET_MESSAGE_FAIL";

export const SENT_MESSAGE_REQ = "SENT_MESSAGE_REQ";
export const SENT_MESSAGE_SUCCESS = "SENT_MESSAGE_SUCCESS";
export const SENT_MESSAGE_FAIL = "LSENT_MESSAGE_FAIL";
