export const LOGIN_USER_REQ = "LOGIN_USER_REQ";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";

export const REGISTER_USER_REQ = "REGISTER_USER_REQ";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOAD_USER_REQ = "LOAD_USER_REQ";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const OTHER_USER_REQ = "OTHER_USER_REQ";
export const OTHER_USER_SUCCESS = "OTHER_USER_SUCCESS";
export const OTHER_USER_FAIL = "OTHER_USER_FAIL";

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
